set -e
true
true
/home/genomika24/miniconda3/envs/genomika/bin/spades-core /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K21/configs/config.info /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K21/configs/isolate_mode.info
/home/genomika24/miniconda3/envs/genomika/bin/spades-core /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K33/configs/config.info /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K33/configs/isolate_mode.info
/home/genomika24/miniconda3/envs/genomika/bin/spades-core /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K55/configs/config.info /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K55/configs/isolate_mode.info
/home/genomika24/miniconda3/envs/genomika/bin/spades-core /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/configs/config.info /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/configs/isolate_mode.info
/home/genomika24/miniconda3/envs/genomika/bin/python3 /home/genomika24/miniconda3/envs/genomika/share/spades/spades_pipeline/scripts/copy_files.py /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/before_rr.fasta /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/before_rr.fasta /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/assembly_graph_after_simplification.gfa /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/assembly_graph_after_simplification.gfa /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/final_contigs.fasta /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/contigs.fasta /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/first_pe_contigs.fasta /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/first_pe_contigs.fasta /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/strain_graph.gfa /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/strain_graph.gfa /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/scaffolds.fasta /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/scaffolds.fasta /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/scaffolds.paths /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/scaffolds.paths /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/assembly_graph_with_scaffolds.gfa /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/assembly_graph_with_scaffolds.gfa /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/assembly_graph.fastg /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/assembly_graph.fastg /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/K77/final_contigs.paths /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/contigs.paths
true
/home/genomika24/miniconda3/envs/genomika/bin/python3 /home/genomika24/miniconda3/envs/genomika/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/scaffolds.fasta --misc_dir /home/genomika24/Dmytro_Boiko/sequence_alignment_cw2/seq_ez_spades_se/misc --threshold_for_breaking_scaffolds 3
true
