set -e
true
true
/home/genomika24/miniconda3/envs/dmytro_boi/bin/spades-hammer /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/corrected/configs/config.info
/home/genomika24/miniconda3/envs/dmytro_boi/bin/python3 /home/genomika24/miniconda3/envs/dmytro_boi/share/spades/spades_pipeline/scripts/compress_all.py --input_file /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/corrected/corrected.yaml --ext_python_modules_home /home/genomika24/miniconda3/envs/dmytro_boi/share/spades --max_threads 16 --output_dir /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/corrected --gzip_output
true
true
/home/genomika24/miniconda3/envs/dmytro_boi/bin/spades-core /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K21/configs/config.info /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K21/configs/careful_mode.info
/home/genomika24/miniconda3/envs/dmytro_boi/bin/spades-core /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K33/configs/config.info /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K33/configs/careful_mode.info
/home/genomika24/miniconda3/envs/dmytro_boi/bin/spades-core /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/configs/config.info /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/configs/careful_mode.info
/home/genomika24/miniconda3/envs/dmytro_boi/bin/python3 /home/genomika24/miniconda3/envs/dmytro_boi/share/spades/spades_pipeline/scripts/copy_files.py /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/before_rr.fasta /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/before_rr.fasta /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/assembly_graph_after_simplification.gfa /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/assembly_graph_after_simplification.gfa /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/final_contigs.fasta /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/contigs.fasta /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/first_pe_contigs.fasta /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/first_pe_contigs.fasta /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/strain_graph.gfa /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/strain_graph.gfa /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/scaffolds.fasta /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/scaffolds.fasta /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/scaffolds.paths /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/scaffolds.paths /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/assembly_graph_with_scaffolds.gfa /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/assembly_graph_with_scaffolds.gfa /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/assembly_graph.fastg /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/assembly_graph.fastg /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/K55/final_contigs.paths /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/contigs.paths
true
true
/home/genomika24/miniconda3/envs/dmytro_boi/bin/python3 /home/genomika24/miniconda3/envs/dmytro_boi/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/contigs.fasta --assembled /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/misc/assembled_contigs.fasta --assembly_type contigs --output_dir /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x --bin_home /home/genomika24/miniconda3/envs/dmytro_boi/bin
/home/genomika24/miniconda3/envs/dmytro_boi/bin/python3 /home/genomika24/miniconda3/envs/dmytro_boi/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/scaffolds.fasta --assembled /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/misc/assembled_scaffolds.fasta --assembly_type scaffolds --output_dir /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x --bin_home /home/genomika24/miniconda3/envs/dmytro_boi/bin
true
/home/genomika24/miniconda3/envs/dmytro_boi/bin/python3 /home/genomika24/miniconda3/envs/dmytro_boi/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/scaffolds.fasta --misc_dir /home/genomika24/dmytro_boi/genome_assembling_home_work2/out_spades_25x/misc --threshold_for_breaking_scaffolds 3
true
