set -e
true
true
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K21/configs/config.info /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K21/configs/careful_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K33/configs/config.info /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K33/configs/careful_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K55/configs/config.info /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K55/configs/careful_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K77/configs/config.info /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K77/configs/careful_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K99/configs/config.info /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K99/configs/careful_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/configs/config.info /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/configs/careful_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/python3 /home/genomika25/miniconda3/envs/genomika/share/spades/spades_pipeline/scripts/copy_files.py /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/before_rr.fasta /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/before_rr.fasta /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/assembly_graph_after_simplification.gfa /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/assembly_graph_after_simplification.gfa /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/final_contigs.fasta /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/contigs.fasta /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/first_pe_contigs.fasta /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/first_pe_contigs.fasta /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/strain_graph.gfa /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/strain_graph.gfa /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/scaffolds.fasta /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/scaffolds.fasta /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/scaffolds.paths /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/scaffolds.paths /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/assembly_graph_with_scaffolds.gfa /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/assembly_graph_with_scaffolds.gfa /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/assembly_graph.fastg /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/assembly_graph.fastg /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/K127/final_contigs.paths /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/contigs.paths
true
true
/home/genomika25/miniconda3/envs/genomika/bin/python3 /home/genomika25/miniconda3/envs/genomika/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/contigs.fasta --assembled /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/misc/assembled_contigs.fasta --assembly_type contigs --output_dir /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly --bin_home /home/genomika25/miniconda3/envs/genomika/bin
/home/genomika25/miniconda3/envs/genomika/bin/python3 /home/genomika25/miniconda3/envs/genomika/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/scaffolds.fasta --assembled /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/misc/assembled_scaffolds.fasta --assembly_type scaffolds --output_dir /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly --bin_home /home/genomika25/miniconda3/envs/genomika/bin
true
/home/genomika25/miniconda3/envs/genomika/bin/python3 /home/genomika25/miniconda3/envs/genomika/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/scaffolds.fasta --misc_dir /home/genomika25/studenci/dmyboi/sequence_adnotation_cw3/spades_assembly/misc --threshold_for_breaking_scaffolds 3
true
