set -e
true
true
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K21/configs/config.info /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K21/configs/isolate_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K33/configs/config.info /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K33/configs/isolate_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K55/configs/config.info /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K55/configs/isolate_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/spades-core /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/configs/config.info /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/configs/isolate_mode.info
/home/genomika25/miniconda3/envs/genomika/bin/python3 /home/genomika25/miniconda3/envs/genomika/share/spades/spades_pipeline/scripts/copy_files.py /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/before_rr.fasta /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/before_rr.fasta /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/assembly_graph_after_simplification.gfa /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/assembly_graph_after_simplification.gfa /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/final_contigs.fasta /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/contigs.fasta /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/first_pe_contigs.fasta /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/first_pe_contigs.fasta /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/strain_graph.gfa /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/strain_graph.gfa /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/scaffolds.fasta /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/scaffolds.fasta /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/scaffolds.paths /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/scaffolds.paths /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/assembly_graph_with_scaffolds.gfa /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/assembly_graph_with_scaffolds.gfa /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/assembly_graph.fastg /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/assembly_graph.fastg /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/K77/final_contigs.paths /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/contigs.paths
true
/home/genomika25/miniconda3/envs/genomika/bin/python3 /home/genomika25/miniconda3/envs/genomika/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/scaffolds.fasta --misc_dir /home/genomika25/studenci/dmyboi/genome_assembling_cw2/out_spades_mp/misc --threshold_for_breaking_scaffolds 3
true
